### PR TITLE
Fix toolbar menus

### PR DESCRIPTION
**Pull request by carolabadeer**

### CODE REVIEW

**Review by kajdreef — CHANGES_REQUESTED** [review]
The keeping one tab open at a time works perfectly! I would love to get these changes merged as soon as possible!

Resetting only doesn't seem to set the tabs to a "default" or initial setting, see image below. I selected a method using the filter and then clicked reset. I would expect to see the visualization to go back to the original state.

image

Would it be possible to extract the changes for keeping one tab open at a time, create a pull request and get those changes merged? The other changes may need to be necessary later on (moving from class to functional component), but at the moment they don't seem to provide a benefit yet. I am hesitant to include the other changes, because I am not sure what the benefits are.

(also you can continue creating changes on this branch and they will appear automatically in the pull request.)

**Comment by carolabadeer** [comment]
I don't think it's possible to revert back to a class component since keeping one tab open requires the setExpanded hook, and hooks are only possible with functional components (that's why I had to do the conversion).

**Comment by kajdreef** [comment]
We should be able to replace the setExpanded hook using setState. In class components, state hooks can be replaced using setState. The tricky part is making sure that when we call `this.setState(...)` we call it using the correct `this`. So I think we could change it something like this (omitted some parts for brevity):

```javascript
constructor(props){
    super();
    this.state = {
            expanded: false,
    }
}

render () {
    const handleChange = (panel) => (event, isExpanded) => {
            const expanded = isExpanded ? panel : false;
            this.setState({
                expanded: expanded,
            });
        }
    return (
        <Accordion expanded={this.state.expanded === 'panel1'} onChange={handleChange('panel1')}></Accordion>
        <Accordion expanded={this.state.expanded === 'panel2'} onChange={handleChange('panel1')}></Accordion>
    )
}
```

What do you think?

**Review by kajdreef — APPROVED** [review]
Looks good! 👍

**Pull request merged**
